"""Constellations and the Observatory night sky: registry, per-cell sky state,
sky generation, and what an activation does.

Data: data/constellations.json (its ``meta.notes`` carry the wiki citations
this module's rules come from). Design: docs/rl-environment.md's width
register for the action block; env/actions.py for the ids.

A night sky is generated by an explicit view action, never on room entry, and
is then **locked** to the star count it was generated at. That timing is the
whole decision the agent gets: higher counts partition into strictly more
value, so drafting every Observatory before looking is worth real resources,
and auto-generating on entry would delete the choice.

Three rules drive generation, all published:

- **True sum-partition, not a threshold.** The set of constellations shown is
  the unique set whose ``stars`` values SUM to the viewing count -- never
  "everything at or below it". ``appearances`` is that partition for 0-49 and
  tools/validate_data.py re-checks the sum for every count.
- **The count is LIVE ``state.stars`` at the moment the sky is first viewed**,
  not the start-of-day ``cfg.stars`` snapshot. This is the opposite convention
  from the Telescope's own spawn gate (effects/items/telescope.py::gate),
  which reads ``cfg.stars`` deliberately so a mid-day star cannot un-gate the
  item until tomorrow. Reusing that convention here would be wrong: the wiki
  states night skies resolve "based on the star count at the time that
  particular night sky is first viewed".
- **Only the first ``max_constellation_skies_per_day`` skies can hold
  constellations.** Later skies are still viewable and come back EMPTY.

``max_constellation_skies_per_day`` is 7 and counts SKIES PER DAY. It has
nothing to do with the fact that the largest single sky in the table also
holds 7 CONSTELLATIONS (at counts 40 and 49) -- see the data file's
"BEWARE TWO UNRELATED SEVENS" note. Collapsing the two would break the
mechanic in opposite directions.

**What an activation does** splits two ways, and the split is in the data. A
record carrying ``grant`` pays an immediate resource delta, applied at the
call site through the shared effects/tier1.py::_grant path. A record carrying
``effect`` does something else, dispatched by :func:`apply_effect` on
``effect.kind``. Every activation is day-scoped: nothing here reaches
env/multiday.py's ``_CARRYOVER_KEYS``, and the permanent star count remains
the only thing a night sky leaves behind.

Two of the kinds write when the constellation fires; the third is read where
it is spent. ``draft_bias`` sets a day-scoped ``GameState`` flag whose
category bias -- and whose published magnitude -- already lives in
data/priority_draws.json. ``entrance_hall_trunks`` spawns containers through
the counter it shares with the ``entrance_hall_trunk`` experiment effect, and
obeys that effect's published cap through the single check on
``SpecialItemsState.add_entrance_hall_trunks``. ``food_step_bonus`` writes
nothing at all: :func:`food_step_bonus` counts today's activations at the
moment a dish's steps resolve, which is what makes it a property of the day
rather than of any one apple.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import experiments

# The two constellations that sit outside the 0-49 partition table. Named here
# only so :meth:`ConstellationsRegistry.sky_at` can find their records; their
# star values (50 and 100) come from the data, never from a literal.
INK_WELL_ID = "ink_well"
SPIRAL_ID = "spiral_of_stars"

# The ``effect.kind`` values :func:`apply_effect` dispatches on. Everything a
# kind needs sits in the record's own ``effect`` block, so no constellation id
# appears in the dispatch and a fourth kind is a data edit plus one ``case``.
EFFECT_DRAFT_BIAS = "draft_bias"  # sets the day-scoped flag a category bias reads
EFFECT_ENTRANCE_HALL_TRUNKS = "entrance_hall_trunks"  # spawns trunks in the Entrance Hall
EFFECT_FOOD_STEP_BONUS = "food_step_bonus"  # raises one items.json dish's base step value


@dataclass(frozen=True)
class Constellation:
    """One data/constellations.json record.

    ``grant_resource``/``grant_amount`` mirror the record's ``grant`` block and
    are ``None``/0 on every record whose effect is not an immediate resource
    delta. ``effect_kind``/``effect`` mirror the record's ``effect`` block and
    are ``None``/empty on every record that grants a resource instead. An
    ``implemented`` record carries exactly one of the two (validate_data.py
    enforces it), so a flipped flag can never mean a silent no-op activation.
    """

    id: str
    name: str
    stars: int
    effect_text: str
    stacks: bool
    implemented: bool
    grant_resource: str | None = None
    grant_amount: int = 0
    effect_kind: str | None = None  # one of the EFFECT_* constants above, or None
    effect: dict = field(default_factory=dict)  # that kind's payload, raw from JSON


@dataclass
class NightSky:
    """One generated night sky, standing at one grid cell for the rest of the day.

    ``stars`` is the live count this sky locked at, kept so the lock is
    inspectable (and testable) rather than implicit. ``activated`` is per-sky,
    which is exactly what lets a second sky at the same Observatory activate
    the same constellation a second time -- the Telescope's documented
    "constellations activate twice".
    """

    source: str  # SOURCE_ROOM or SOURCE_HELD -- which telescope generated it
    stars: int
    constellation_ids: tuple[str, ...]
    activated: set[str] = field(default_factory=set)

    def unactivated(self) -> tuple[str, ...]:
        """Ids in this sky not yet activated, in record order."""
        return tuple(c for c in self.constellation_ids if c not in self.activated)


# The two viewing sources, in the order view_night_sky spends them. The room's
# own telescope is free and always there; a held Telescope adds one extra sky
# per Observatory, so spending the free one first can never strand it.
#
# These name WHICH telescope, not the room or the item -- deliberately not the
# "observatory"/"telescope" ids, which would hardcode a room id and an item id
# into an engine module (tests/test_room_id_allowlist.py,
# tests/test_item_id_allowlist.py). The room is reached through
# Capability.NIGHT_SKY and the item through effects/items/telescope.py::held.
SOURCE_ROOM = "room"
SOURCE_HELD = "held"


@dataclass(frozen=True)
class ConstellationsRegistry:
    """Parsed data/constellations.json: records in file order, plus the table."""

    records: tuple[Constellation, ...]
    by_id: dict[str, Constellation]
    index_by_id: dict[str, int]
    appearances: dict[int, tuple[str, ...]]
    max_skies_per_day: int
    max_constellation_skies_per_day: int

    @property
    def table_max(self) -> int:
        """Highest star count the ``appearances`` partition table covers (49)."""
        return max(self.appearances)

    def _ordered(self, ids) -> tuple[str, ...]:
        """Sort ids into record order, the order the action block indexes by."""
        return tuple(sorted(set(ids), key=lambda c: self.index_by_id[c]))

    def _repeat(self, offset: int) -> tuple[str, ...]:
        """The 0-49 partition repeating at ``offset`` above a band's base.

        Offset 0 contributes NOTHING, and that is the whole reason this is not
        a bare ``appearances[offset]``. Count 0 is the table's one entry that
        does not sum to its key -- it positively asserts the North Star (1
        star) for a player who drafted an Observatory and then lost every
        star. Reused as a band remainder it would add a phantom star, making a
        50-star sky the Ink Well PLUS the North Star and summing to 51.
        """
        return () if offset == 0 else self.appearances[offset]

    def sky_at(self, stars: int) -> tuple[str, ...]:
        """The constellations a sky first viewed at ``stars`` shows, in record order.

        0..49 is the ``appearances`` table verbatim. Above it the data file's
        own note applies: from the Ink Well's 50 stars it appears at every
        count while the table repeats 50 lower, from the Spiral's 100 the
        Spiral does the same (and the Ink Well drops out until 150, where both
        appear). Stars carry across days and accumulate save-scoped, so these
        bands are reachable in a long attempt and this function has to be
        total over them rather than raise.

        At and above Spiral + Ink Well + one table span the star values no
        longer sum to the count at all, so no partition exists and the wiki
        publishes none: the sky is empty. Reaching it needs ~200 Observatory
        drafts, so this is a guard against an undefined KeyError, not a
        modelled mechanic.
        """
        if stars < 0:
            stars = 0
        span = self.table_max + 1  # 50: the table covers 0..49
        ink = self.by_id[INK_WELL_ID].stars  # 50
        spiral = self.by_id[SPIRAL_ID].stars  # 100
        if stars < span:
            return self.appearances[stars]
        if stars < spiral:
            return self._ordered((INK_WELL_ID, *self._repeat(stars - ink)))
        if stars < spiral + span:
            return self._ordered((SPIRAL_ID, *self._repeat(stars - spiral)))
        if stars < spiral + ink + span:
            return self._ordered(
                (SPIRAL_ID, INK_WELL_ID, *self._repeat(stars - spiral - ink)))
        return ()


def load_constellations(data_dir: Path) -> ConstellationsRegistry:
    """Parse data/constellations.json into a :class:`ConstellationsRegistry`.

    Record order is preserved exactly: it is the single source for the
    ACTIVATE_CONSTELLATION_BASE action block and the ``constellations``
    observation key, so this loader must never sort or filter.
    """
    doc = json.loads((data_dir / "constellations.json").read_text(encoding="utf-8"))
    records = tuple(
        Constellation(
            id=r["id"],
            name=r["name"],
            stars=r["stars"],
            effect_text=r["effect_text"],
            stacks=r["stacks"],
            implemented=r.get("implemented", False),
            grant_resource=(r.get("grant") or {}).get("resource"),
            grant_amount=(r.get("grant") or {}).get("amount", 0),
            effect_kind=(r.get("effect") or {}).get("kind"),
            effect=dict(r.get("effect") or {}),
        )
        for r in doc["constellations"]
    )
    return ConstellationsRegistry(
        records=records,
        by_id={c.id: c for c in records},
        index_by_id={c.id: i for i, c in enumerate(records)},
        appearances={int(k): tuple(v) for k, v in doc["appearances"].items()},
        max_skies_per_day=doc["max_skies_per_day"],
        max_constellation_skies_per_day=doc["max_constellation_skies_per_day"],
    )


def skies_generated(state) -> int:
    """How many night skies have been generated today, across every cell.

    Derived from ``state.night_skies`` rather than kept as its own counter, so
    the per-day caps and the observation can never disagree with the skies
    that actually exist.
    """
    return sum(len(v) for v in state.night_skies.values())


def activation_count(state, constellation_id: str) -> int:
    """How many times ``constellation_id`` has been activated today.

    Counts across every sky at every cell: two skies at one Observatory (the
    room's telescope plus a held Telescope) each hold their own activation, so
    the same constellation genuinely fires twice.
    """
    return sum(
        1
        for skies in state.night_skies.values()
        for sky in skies
        if constellation_id in sky.activated
    )


def unused_source(state, cell: int, telescope_held: bool) -> str | None:
    """The next viewing source available at ``cell``, or None if both are spent.

    Each Observatory offers its own telescope once, and a held Telescope
    "generates an additional night sky for each Observatory it is used in" --
    so the sources are per-cell, not per-day, and a second Observatory
    re-offers both.
    """
    used = {sky.source for sky in state.night_skies.get(cell, ())}
    if SOURCE_ROOM not in used:
        return SOURCE_ROOM
    if telescope_held and SOURCE_HELD not in used:
        return SOURCE_HELD
    return None


def generate_sky(registry: ConstellationsRegistry, state, cell: int, source: str) -> NightSky:
    """Generate one night sky at ``cell`` and record it against the day.

    Resolves at LIVE ``state.stars`` -- see the module docstring for why that
    is not ``cfg.stars``. A sky generated past
    ``max_constellation_skies_per_day`` is still a real, viewed sky; it just
    holds no constellations ("if an eighth night sky is viewed, it is always
    empty").
    """
    if skies_generated(state) < registry.max_constellation_skies_per_day:
        shown = registry.sky_at(state.stars)
    else:
        shown = ()
    sky = NightSky(source=source, stars=state.stars, constellation_ids=shown)
    state.night_skies.setdefault(cell, []).append(sky)
    return sky


def _times_applied(state, record: Constellation) -> int:
    """Today's activations of ``record``, capped at 1 when it does not stack.

    The multiplier for effects that are READ rather than written -- a bonus
    counted at the moment it is spent, not banked when the constellation
    fires. Written effects need the same rule expressed as a yes/no instead;
    :func:`apply_effect` carries that one.
    """
    times = activation_count(state, record.id)
    return times if record.stacks else min(times, 1)


def apply_effect(game, record: Constellation) -> None:
    """Apply one activation of ``record``'s ``effect`` block.

    Called from Game.activate_constellation AFTER the activation is recorded
    on its sky, so :func:`activation_count` already counts this one. Records
    carrying a ``grant`` instead have no ``effect`` block and reach this as a
    no-op; their payout goes through the shared effects/tier1.py::_grant path
    at the call site, exactly as before.

    Takes ``game`` duck-typed, no import of Game, for the same reason
    experiments.py::apply_effect does: this module is imported by state.py and
    must stay free of that cycle.
    """
    state = game.state
    if record.effect_kind is None:
        return
    # A non-stacking record's second activation must not re-run anything
    # additive -- the held Telescope's extra sky is documented as worth nothing
    # for these. Setting a day-scoped flag twice would be harmless, but the
    # guard belongs to every kind rather than to the ones that happen to
    # notice, so it sits here and not inside a branch.
    if not record.stacks and activation_count(state, record.id) > 1:
        return
    if record.effect_kind == EFFECT_DRAFT_BIAS:
        # The condition tag is the join to the priority_draws.json
        # category_biases entry that owns the magnitude; draft.py's
        # _active_conditions re-derives the tag from these flags on every draw,
        # so activation is a one-line write and the bias is already wired.
        match record.effect["condition"]:
            case "southern_cross_constellation":
                state.southern_cross_active = True
            case "draxus_constellation":
                state.draxus_active = True
    elif record.effect_kind == EFFECT_ENTRANCE_HALL_TRUNKS:
        state.special.add_entrance_hall_trunks(
            experiments.entrance_hall_trunk_cap(game.registry),
            record.effect["trunks"])
    # EFFECT_FOOD_STEP_BONUS deliberately writes nothing here:
    # :func:`food_step_bonus` reads the activation count where a dish's steps
    # resolve, so the bonus needs no counter of its own and applies to apples
    # eaten before the activation as well as after -- which is what "apples are
    # extra delicious today" says, a property of the day, not of the apple.


def food_step_bonus(registry: ConstellationsRegistry, state, food_id: str) -> int:
    """Extra base steps one serving of ``food_id`` gets from today's activations.

    Data-keyed on the dish, so nothing here names apples: every record whose
    ``effect`` is a ``food_step_bonus`` for this dish contributes its own
    ``steps`` once per counted activation. Added to the dish's BASE, before
    special_items.py::food_steps folds in the Salt Shaker and Silver Spoon --
    see the Farmer's Apple record's note for the published worked example that
    pins that order.
    """
    return sum(
        record.effect.get("steps", 0) * _times_applied(state, record)
        for record in registry.records
        if record.effect_kind == EFFECT_FOOD_STEP_BONUS
        and record.effect.get("food_id") == food_id
    )
