"""Constellations and the Observatory night sky: registry, per-cell sky state,
and sky generation.

Data: data/constellations.json (its ``meta.notes`` carry the wiki citations
this module's rules come from). Design: docs/rl-environment.md's width
register for the action block; env/actions.py for the ids.

A night sky is generated by an explicit view action, never on room entry, and
is then **locked** to the star count it was generated at. That timing is the
whole decision the agent gets: higher counts partition into strictly more
value, so drafting every Observatory before looking is worth real resources,
and auto-generating on entry would delete the choice.

Three rules drive generation, all published:

- **True sum-partition, not a threshold.** The set of constellations shown is
  the unique set whose ``stars`` values SUM to the viewing count -- never
  "everything at or below it". ``appearances`` is that partition for 0-49 and
  tools/validate_data.py re-checks the sum for every count.
- **The count is LIVE ``state.stars`` at the moment the sky is first viewed**,
  not the start-of-day ``cfg.stars`` snapshot. This is the opposite convention
  from the Telescope's own spawn gate (effects/items/telescope.py::gate),
  which reads ``cfg.stars`` deliberately so a mid-day star cannot un-gate the
  item until tomorrow. Reusing that convention here would be wrong: the wiki
  states night skies resolve "based on the star count at the time that
  particular night sky is first viewed".
- **Only the first ``max_constellation_skies_per_day`` skies can hold
  constellations.** Later skies are still viewable and come back EMPTY.

``max_constellation_skies_per_day`` is 7 and counts SKIES PER DAY. It has
nothing to do with the fact that the largest single sky in the table also
holds 7 CONSTELLATIONS (at counts 40 and 49) -- see the data file's
"BEWARE TWO UNRELATED SEVENS" note. Collapsing the two would break the
mechanic in opposite directions.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

# The two constellations that sit outside the 0-49 partition table. Named here
# only so :meth:`ConstellationsRegistry.sky_at` can find their records; their
# star values (50 and 100) come from the data, never from a literal.
INK_WELL_ID = "ink_well"
SPIRAL_ID = "spiral_of_stars"


@dataclass(frozen=True)
class Constellation:
    """One data/constellations.json record.

    ``grant_resource``/``grant_amount`` mirror the record's ``grant`` block and
    are ``None``/0 on every record whose effect is not an immediate resource
    delta. Every record carrying a grant is ``implemented``; the rest are not.
    """

    id: str
    name: str
    stars: int
    effect_text: str
    stacks: bool
    implemented: bool
    grant_resource: str | None = None
    grant_amount: int = 0


@dataclass
class NightSky:
    """One generated night sky, standing at one grid cell for the rest of the day.

    ``stars`` is the live count this sky locked at, kept so the lock is
    inspectable (and testable) rather than implicit. ``activated`` is per-sky,
    which is exactly what lets a second sky at the same Observatory activate
    the same constellation a second time -- the Telescope's documented
    "constellations activate twice".
    """

    source: str  # SOURCE_ROOM or SOURCE_HELD -- which telescope generated it
    stars: int
    constellation_ids: tuple[str, ...]
    activated: set[str] = field(default_factory=set)

    def unactivated(self) -> tuple[str, ...]:
        """Ids in this sky not yet activated, in record order."""
        return tuple(c for c in self.constellation_ids if c not in self.activated)


# The two viewing sources, in the order view_night_sky spends them. The room's
# own telescope is free and always there; a held Telescope adds one extra sky
# per Observatory, so spending the free one first can never strand it.
#
# These name WHICH telescope, not the room or the item -- deliberately not the
# "observatory"/"telescope" ids, which would hardcode a room id and an item id
# into an engine module (tests/test_room_id_allowlist.py,
# tests/test_item_id_allowlist.py). The room is reached through
# Capability.NIGHT_SKY and the item through effects/items/telescope.py::held.
SOURCE_ROOM = "room"
SOURCE_HELD = "held"


@dataclass(frozen=True)
class ConstellationsRegistry:
    """Parsed data/constellations.json: records in file order, plus the table."""

    records: tuple[Constellation, ...]
    by_id: dict[str, Constellation]
    index_by_id: dict[str, int]
    appearances: dict[int, tuple[str, ...]]
    max_skies_per_day: int
    max_constellation_skies_per_day: int

    @property
    def table_max(self) -> int:
        """Highest star count the ``appearances`` partition table covers (49)."""
        return max(self.appearances)

    def _ordered(self, ids) -> tuple[str, ...]:
        """Sort ids into record order, the order the action block indexes by."""
        return tuple(sorted(set(ids), key=lambda c: self.index_by_id[c]))

    def _repeat(self, offset: int) -> tuple[str, ...]:
        """The 0-49 partition repeating at ``offset`` above a band's base.

        Offset 0 contributes NOTHING, and that is the whole reason this is not
        a bare ``appearances[offset]``. Count 0 is the table's one entry that
        does not sum to its key -- it positively asserts the North Star (1
        star) for a player who drafted an Observatory and then lost every
        star. Reused as a band remainder it would add a phantom star, making a
        50-star sky the Ink Well PLUS the North Star and summing to 51.
        """
        return () if offset == 0 else self.appearances[offset]

    def sky_at(self, stars: int) -> tuple[str, ...]:
        """The constellations a sky first viewed at ``stars`` shows, in record order.

        0..49 is the ``appearances`` table verbatim. Above it the data file's
        own note applies: from the Ink Well's 50 stars it appears at every
        count while the table repeats 50 lower, from the Spiral's 100 the
        Spiral does the same (and the Ink Well drops out until 150, where both
        appear). Stars carry across days and accumulate save-scoped, so these
        bands are reachable in a long attempt and this function has to be
        total over them rather than raise.

        At and above Spiral + Ink Well + one table span the star values no
        longer sum to the count at all, so no partition exists and the wiki
        publishes none: the sky is empty. Reaching it needs ~200 Observatory
        drafts, so this is a guard against an undefined KeyError, not a
        modelled mechanic.
        """
        if stars < 0:
            stars = 0
        span = self.table_max + 1  # 50: the table covers 0..49
        ink = self.by_id[INK_WELL_ID].stars  # 50
        spiral = self.by_id[SPIRAL_ID].stars  # 100
        if stars < span:
            return self.appearances[stars]
        if stars < spiral:
            return self._ordered((INK_WELL_ID, *self._repeat(stars - ink)))
        if stars < spiral + span:
            return self._ordered((SPIRAL_ID, *self._repeat(stars - spiral)))
        if stars < spiral + ink + span:
            return self._ordered(
                (SPIRAL_ID, INK_WELL_ID, *self._repeat(stars - spiral - ink)))
        return ()


def load_constellations(data_dir: Path) -> ConstellationsRegistry:
    """Parse data/constellations.json into a :class:`ConstellationsRegistry`.

    Record order is preserved exactly: it is the single source for the
    ACTIVATE_CONSTELLATION_BASE action block and the ``constellations``
    observation key, so this loader must never sort or filter.
    """
    doc = json.loads((data_dir / "constellations.json").read_text(encoding="utf-8"))
    records = tuple(
        Constellation(
            id=r["id"],
            name=r["name"],
            stars=r["stars"],
            effect_text=r["effect_text"],
            stacks=r["stacks"],
            implemented=r.get("implemented", False),
            grant_resource=(r.get("grant") or {}).get("resource"),
            grant_amount=(r.get("grant") or {}).get("amount", 0),
        )
        for r in doc["constellations"]
    )
    return ConstellationsRegistry(
        records=records,
        by_id={c.id: c for c in records},
        index_by_id={c.id: i for i, c in enumerate(records)},
        appearances={int(k): tuple(v) for k, v in doc["appearances"].items()},
        max_skies_per_day=doc["max_skies_per_day"],
        max_constellation_skies_per_day=doc["max_constellation_skies_per_day"],
    )


def skies_generated(state) -> int:
    """How many night skies have been generated today, across every cell.

    Derived from ``state.night_skies`` rather than kept as its own counter, so
    the per-day caps and the observation can never disagree with the skies
    that actually exist.
    """
    return sum(len(v) for v in state.night_skies.values())


def activation_count(state, constellation_id: str) -> int:
    """How many times ``constellation_id`` has been activated today.

    Counts across every sky at every cell: two skies at one Observatory (the
    room's telescope plus a held Telescope) each hold their own activation, so
    the same constellation genuinely fires twice.
    """
    return sum(
        1
        for skies in state.night_skies.values()
        for sky in skies
        if constellation_id in sky.activated
    )


def unused_source(state, cell: int, telescope_held: bool) -> str | None:
    """The next viewing source available at ``cell``, or None if both are spent.

    Each Observatory offers its own telescope once, and a held Telescope
    "generates an additional night sky for each Observatory it is used in" --
    so the sources are per-cell, not per-day, and a second Observatory
    re-offers both.
    """
    used = {sky.source for sky in state.night_skies.get(cell, ())}
    if SOURCE_ROOM not in used:
        return SOURCE_ROOM
    if telescope_held and SOURCE_HELD not in used:
        return SOURCE_HELD
    return None


def generate_sky(registry: ConstellationsRegistry, state, cell: int, source: str) -> NightSky:
    """Generate one night sky at ``cell`` and record it against the day.

    Resolves at LIVE ``state.stars`` -- see the module docstring for why that
    is not ``cfg.stars``. A sky generated past
    ``max_constellation_skies_per_day`` is still a real, viewed sky; it just
    holds no constellations ("if an eighth night sky is viewed, it is always
    empty").
    """
    if skies_generated(state) < registry.max_constellation_skies_per_day:
        shown = registry.sky_at(state.stars)
    else:
        shown = ()
    sky = NightSky(source=source, stars=state.stars, constellation_ids=shown)
    state.night_skies.setdefault(cell, []).append(sky)
    return sky
